# Generated by Django 5.0.2 on 2024-03-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoVlogApp', '0006_publicacion_esthumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='esThumb',
            new_name='esThumbLugares',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='esThumbCategorias',
            field=models.BooleanField(default=False),
        ),
    ]
